create database `E-Commerce Sales Analysis`;
use `E-Commerce Sales Analysis`;

-- Q1. Find all orders placed by customers from Delhi.
select o.*, c.city
from orders o
join customers c 
on c.customer_id = o.customer_id
where c.city ='Delhi';

-- Q2. Find products with price greater than ₹10,000.
select product_name, price
from products
where price > 10000;

-- Q3. Find orders where quantity is greater than or equal to 2.
select *
from orders 
where quantity >= '2';

-- Q4. Calculate total revenue.
select sum(o.quantity * p.price) as Total_revenue
from orders o 
join products p 
on o.product_id = p.product_id;

-- Q5. Find total number of orders.
select count(*) as Total_orders
from orders;

-- Q6. Find total quantity sold.
select sum(quantity) as Total_quantity_sold
from orders;

-- Q7. Find average product price.
select avg(price) as Average_product_price
from products;

-- Q8. Find the highest-priced product.
select max(price) as Highest_priced_product
from products;

-- Q9. Find total spending of each customer.
select c.customer_id, c.customer_name, sum(o.quantity * p.price) as total_spending
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.customer_id, c.customer_name;

-- Q10. Find the customer who spent the most money.
select c.customer_id, c.customer_name, sum(p.price) as Total_spent
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.customer_id, c.customer_name
order by Total_spent desc
limit 1;

-- Q11. Find the top 5 customers by spending.
select c.customer_id, c.customer_name, sum(p.price) as Total_spending
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.customer_id, c.customer_name
order by Total_spending desc
limit 5;

-- Q12. Find the number of orders placed by each customer.
select c.customer_id, c.customer_name, count(o.order_id) as Total_orders
from customers c 
join orders o 
on c.customer_id = o.customer_id
group by c.customer_id, c.customer_name;

-- Q13. Find total quantity sold for each product.
select p.product_id, p.product_name, sum(o.quantity) as total_quantity
from products p 
join orders o 
on p.product_id = p.product_id
group by p.product_id, p.product_name;

-- Q14. Find total revenue generated by each product.
 select p.product_id, p.product_name, sum(o.quantity * p.price) as Total_revenue
 from products p 
 join orders o 
 on p.product_id = o.product_id
 group by product_id, product_name;
 
--  Q15. Find the best-selling product by quantity.
select p.product_id, p.product_name, sum(o.quantity) as Best_selling_product
from products p 
join orders o 
on p.product_id = o.product_id
group by p.product_id, p.product_name
order by Best_selling_product desc 
limit 1;

-- Q16. Find the highest-revenue product.
select p.product_id, p.product_name, sum(p.price * o.quantity) as Highest_revenue
from products p
join orders o 
on p.product_id = o.product_id
group by p.product_id, p.product_name
order by Highest_revenue desc
limit 1;

-- Q17. Find category-wise revenue.
select p.category, sum(p.price * o.quantity) as Total_revenue
from products p 
join orders o 
on p.product_id = o.product_id
group by p.category
order by Total_revenue desc;

-- Q18. Find total revenue by city.
select c.city, sum(o.quantity * p.price) as Total_revenue
from customers c
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.city
order by Total_revenue desc;

-- Q19. Find the city with the highest revenue.
select c.city, sum(o.quantity * p.price) as Highest_revenue
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.city
order by Highest_revenue desc 
limit 1;

-- Q20. Find the number of customers in each city.
select city, count(customer_id) as Total_customer
from customers
group by city;

-- Q21. Find the average spending of customers in each city.
select c.customer_id, c.city, avg(o.quantity * p.price) as Average_spending
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.city, c.customer_id;

-- Q22. Find the top 3 cities by revenue.
select c.city, sum(o.quantity * p.price) as Total_revenue
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.city
order by Total_revenue desc
limit 3;

-- Q23. Categorize products based on price:
select product_id, product_name, price,
case 
    when price >= 50000 then 'High'
    when price >= 10000 then 'Medium'
    else 'Low'
end as price_category
from products;

-- Q24. Categorize customers based on spending:
select c.customer_id, c.customer_name, sum(o.quantity * p.price) as Total_spending,
case 
    when sum(o.quantity * p.price) >= 50000 then 'Premium'
    when sum(o.quantity * p.price) >= 10000 then 'Regular'
    else 'Basic'
end as Spending_category
from customers c 
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.customer_id, c.customer_name;

-- Q25. Find products whose revenue is greater than average product revenue.
select p.product_id, p.product_name, sum(o.quantity * p.price) as Total_revenue
from products p
join orders o 
on p.product_id = o.product_id
group by p.product_id, p.product_name
having sum(o.quantity * p.price) > (
select avg(Product_revenue)
from (
select sum(o2.quantity * p2.price) as Product_revenue
from products p2
join orders o2
on p2.product_id = o2.product_id
group by p2.product_id
) as Revenue_table
);

-- Q26. Find the second-highest spending customer.
select c.customer_id, c.customer_name, sum(o.quantity * p.price) as Total_spending
from customers c
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.customer_id, c.customer_name
order by Total_spending desc
limit 1 offset 1;

-- Q27. Find the top 3 customers using RANK().
select * 
from (
 select c.customer_id, c.customer_name, sum(o.quantity * p.price) as Total_spending,
 rank() over(
  order by sum(o.quantity * p.price) desc
  ) as Customer_rank
from customers c
join orders o 
on c.customer_id = o.customer_id
join products p 
on o.product_id = p.product_id
group by c.customer_id, c.customer_name
) as Ranked_customer
where Customer_rank <= 3;

-- Q28. Find the highest-revenue product in each category.
select *
from (
 select p.category, p.product_id, p.product_name, sum(o.quantity * p.price) as Total_revenue,
 rank() over(
 partition by p.category
 order by sum(o.quantity * p.price) desc
) as Revenue_rank
from products p
join orders o 
on p.product_id = o.product_id
group by  p.category, p.product_id, p.product_name
) as Ranked_products
where Revenue_rank = 1;

-- Q29. Create a CTE that calculates customer-wise total revenue.
with customer_revenue as (
 select c.customer_id, c.customer_name, sum(o.quantity * p.price) as Total_revenue
 from customers c 
 join orders o 
 on c.customer_id = o.customer_id
 join products p 
 on o.product_id = p.product_id
 group by c.customer_id, c.customer_name
)
select * from customer_revenue;

 
select * from orders;
select * from customers;
select * from products;